#!/usr/bin/env bash
pactl unload-module module-echo-cancel
pactl load-module module-echo-cancel aec_method=webrtc source_name=echocancel sink_name=echocancel_sink
pacmd set-default-source echocancel
pacmd set-default-sink echocancel_sink
